### ISSUE TITLE
Possible problem together with deCONZ 

### ISSUE THREAD

**Issue by skeptizzle** [custom-components/custom_updater#101]
https://community.home-assistant.io/t/deconz-official-thread/100504

**Comment by ludeeus** [comment]
As described in the issue template issues missing required information will be closed.
In this issue these are missing:

- Component version
- Debug logs
- Component configuration
- Lovelace configuration
- Proper description

**Comment by skeptizzle** [comment]
I'm sorry. The issue template didn't show on mobile, so I though there were none.

**Comment by ludeeus** [comment]
Ah...
Add the info to this issue and I can take a look, or create a new one to get the template.

**Comment by skeptizzle** [comment]
First thing tomorrow.

Cheers!

**Comment by skeptizzle** [comment]
Hi @ludeeus

Just letting you know that I removed all my custom_components and all of custom_updater and I still experience problems with deCONZ integration after reboot, so as far as my installation, your custom_component has nothing to do with deCONZ not working..
