### ISSUE TITLE
FEATURE: Show installable elements

### ISSUE THREAD

**Issue by ludeeus** [custom-components/custom_updater#103]
Related to #102 

For now `show_installable` does not do anything, personally I found it confusing to see all these elements.
It was added as a preparation to easy install elements from the tracker-card but I have given up on that.

As of now, I see two options:
- Add the logic back to present **all** elements.
- Remove the config option.

Add your reaction to this FR with:
 👍 for "Add the logic back to present **all** elements."
👎 for "Remove the config option."
🚀 for "I don't have an opinion"

**Comment by elRadix** [comment]
please add this feature, I want to see all items so that I can try them and discover new ones something like a custom card/component store 😄

**Comment by ludeeus** [comment]
@elRadix I will not add this to this component, but that is in the scope of ["HACS"](https://github.com/custom-components/hacs)

It's funny that you wrote this 10 min before I posted https://github.com/custom-components/custom_updater/issues/117
