### ISSUE TITLE
After last update of custom updater tracker card and custom weather card not working

### ISSUE THREAD

**Issue by Obicom** [custom-components/custom_updater#106]
## Version of the custom_component
Version not known. Last update 2 hours ago.

## Describe the bug
after last update (done via tracker card) custom weather card and tracker card are not available. Custom updater shows a error on HA.

## `custom_updater` configuration

![image](https://user-images.githubusercontent.com/25134482/53440962-13540900-3a06-11e9-8581-cd06a6a8a335.png)

# Add configuration here

![image](https://user-images.githubusercontent.com/25134482/53441063-49918880-3a06-11e9-97dd-64097b264ff7.png)

## Resources in lovelace configuration

![image](https://user-images.githubusercontent.com/25134482/53441144-70e85580-3a06-11e9-8423-2ca4ea23e3b6.png)

**Comment by ludeeus** [comment]
remove `mode` from config, then restart HA.

**Comment by Obicom** [comment]
I did but without success

![image](https://user-images.githubusercontent.com/25134482/53441507-44810900-3a07-11e9-8c0e-d3d06132c0de.png)

**Comment by Obicom** [comment]
Here the error from log:

![image](https://user-images.githubusercontent.com/25134482/53441660-945fd000-3a07-11e9-9461-305776439271.png)

**Comment by Obicom** [comment]
Saw latest version, updated and now it works (4.2.15)
