### ISSUE TITLE
Uploading of custom_updater.py causes love lace front end to e non responsive

### ISSUE THREAD

**Issue by Silvrav** [custom-components/custom_updater#107]
## Version of the custom_component
Latest as per (dl 6hours ago): https://github.com/custom-components/custom_updater/tree/master/custom_components

## Describe the bug
So I add the code to configuration.yaml and did a restart to test - no issue, front end (lovelve) works fine except with the error of custom_updater component not found. Upload file (custom_updater.py) to /config/custom_components/ and restart hassio - after restart front end (lovelace) is non responsive. I can still access configurator or samba or connect via SSH. Remove file, restart hassio via SSH and frontend works again

## `custom_updater` configuration
In configuration file its:

`custom_updater:`

also tried

```
custom_updater:
  track:
    - components
    - cards
    - python_scripts
```

# Add configuration here

```

## Resources in lovelace configuration

```yaml

# Add configuration here

```

## Tracker-card configuration

Not added yet as cant get custom updater to start

# Add configuration here

Not added yet as cant get custom updater to start
```

## Debug log
<!-- https://github.com/custom-components/custom_updater/wiki/Debug -->

cant get past start up for deubg to work

Add your logs here.

```

**Comment by ludeeus** [comment]
Check the homeassistant log file ;)

**Comment by Silvrav** [comment]
`2019-02-27 14:10:55 ERROR (MainThread) [homeassistant.components.hassio] Error on Hass.io API: 
2019-02-27 14:10:55 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall homeassistant.restart (c:2a19dfba0d0e43b0877a5dd7d1dc53a3)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1142, in _safe_execute
    await self._execute_service(handler, service_call)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1155, in _execute_service
    await handler.func(service_call)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/hassio/__init__.py", line 268, in async_handle_core_service
    error = await async_check_config(hass)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/hassio/__init__.py", line 148, in async_check_config
    raise HomeAssistantError() from None
homeassistant.exceptions.HomeAssistantError`

THe error portion from the log

**Comment by ludeeus** [comment]
You have a configuration error.
run config check

**Comment by Silvrav** [comment]
> You have a configuration error.
> run config check

config check passes if i comment out custom_updater: from the yaml file.
even if i dont it does restart fine with custom_updater: in the config file.

It only refuses to start up as soon as I Upload file (custom_updater.py) to /config/custom_components/

**Comment by ludeeus** [comment]
From what I see it does not even load it (there are no references to it in your log.)
Unless you can find logs containing this component there is nothing I can do.

https://github.com/custom-components/custom_updater/wiki/Debug

**Comment by Silvrav** [comment]
Ill try the debug again tonight as soon as I am home
