### ISSUE TITLE
custom updater shows update available after ha restart

### ISSUE THREAD

**Issue by h4nc** [custom-components/custom_updater#111]
Since the last update of custom updater, it shows me update available after each ha restart.
And of course there is no update available.

Does someone else have that issue too?

custom updater version 4.2.15
ha 0.88.1

**Comment by ludeeus** [comment]
As described in the issue template issues missing required information will be closed.
In this issue these are missing:

- Debug logs
- Component configuration
- Lovelace configuration
- Proper description
