### ISSUE TITLE
not accepting storage mode

### ISSUE THREAD

**Issue by gnkarn** [custom-components/custom_updater#113]
## Describe the bug
Invalid config for [custom_updater]: [mode] is an invalid option for [custom_updater]. Check: custom_updater->custom_updater->mode. (See /config/configuration.yaml, line 630). Please check the docs at https://home-assistant.io/components/custom_updater/

## `custom_updater` configuration

```custom_updater:
  mode: storage
  track:
    - cards
    - components
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/bramkragten/custom-ui/master/updater.json 
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json

# Add configuration here

```

## Resources in lovelace configuration

```yaml

# Add configuration here

```

## Tracker-card configuration

```yaml

# Add configuration here

```

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
That is no longer valid, remove it.

**Comment by cwhits** [comment]
@ludeeus can you edit the release notes for the 4.0.0 tag? they still reference adding `mode: storage`

**Comment by ludeeus** [comment]
For 4.0.0 it's still vaild
