### ISSUE TITLE
updater do not update from 4.2.15 to 4.2.16

### ISSUE THREAD

**Issue by gnkarn** [custom-components/custom_updater#114]
## Describe the bug
just as the title states ., when selecting update all, it just stays unchanged .

## `custom_updater` configuration

```yaml

# Add configuration here

```

## Resources in lovelace configuration

```yaml

# Add configuration here

```

## Tracker-card configuration

```yaml

# Add configuration here

```

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
it's a component, you need to restart HA for it to finish the upgrade and load the new version.
