### ISSUE TITLE
4.2.16 available but not downloaded/installed

### ISSUE THREAD

**Issue by DavidFW1960** [custom-components/custom_updater#115]
Tracker card says 4.2.16 is available but it's not updating to that. I see on releases page 4.2.15 is the latest but I see the 4.2.16 commit on the code page....

**Comment by DavidFW1960** [comment]
In fact. 4.2.16 has been downloaded and installed, tracker card just isn't seeing it as updated.
![image](https://user-images.githubusercontent.com/36390762/53672632-81831f00-3cd7-11e9-9cc4-96b4ce1df70f.png)

**Comment by ludeeus** [comment]
https://github.com/custom-components/custom_updater/issues/114

**Comment by DavidFW1960** [comment]
hahahaha!!!

I was just coming back in to say I restarted home-assistant and it's updated. LOL!!

Thanks.

**Comment by ludeeus** [comment]
> "it's a feature, not a bug"

_- Every developer_

["more" info](https://github.com/custom-cards/tracker-card/issues/52)
