### ISSUE TITLE
Remove ambiguity about "Update Available" after an update all.

### ISSUE THREAD

**Issue by GaryOkie** [custom-components/custom_updater#116]
## Is your feature request related to a problem? Please describe.
The new "feature" in custom_updater to not indicate in any way that an update has actually occurred should be improved for clarity, especially since this is a change from previous behavior  (see #115 #114, #112 ...).   

Users see "Update Available" in red,  click "Update All", and still see the exact same "Update Available".   No indication that the component/card has actually been updated.   Please no longer show that an update is still available, when it really isn't. 

## Describe the solution you'd like
After an "Update All",  provide a clear indication that the component(s) have been updated and that a restart is required for the update to take effect.

Example (before update):

**Name ___________________ Current  _____ Available**

**Custom Components**
  custom_updater __________ 4.2.15 ______ **4.2.16**
  device_tracker.life360 ____ 2.8.0 ________ 2.8.0

Click "**UPDATE ALL**"

Table now shows: 

**Name ___________________ Current  _____ Available**

**Custom Components**
  custom_updater __________ 4.2.16 ______ 4.2.16  
  device_tracker.life360 ____ 2.8.0 ________ 2.8.0

 **HA Restart Required for update to reload**

**Comment by ludeeus** [comment]
The previous method was wrong, you are not using the updated version before you restart Home Assistant, components/platforms are loaded on home assistant startup.

**Comment by GaryOkie** [comment]
Yes, I understand the updated code is not loaded until there is a restart!    

The updater needs to indicate that the actual code update was successful and not leave you wondering if there was a problem with it not working since it still shows the update as "available" after it was updated (until you restart).

I think it is probably well understood by most users that a restart is required after a code update, but it would be a good idea to state that a restart is required via an added message. 

The main issue here is simply to avoid the confusion with the table still saying "Update Available" when the code update has successfully occurred.

**Comment by Ernst79** [comment]
I was also confused and thought that the component was not updated for some reason I didn’t understand. I had similar similar behavior if a custom component was not owned by the home assistant user, so I was already searching for something like that. A “restart is required message” would be helpful.
