### ISSUE TITLE
🚨 Partial "Deprecation" notice🚨

### ISSUE THREAD

**Issue by ludeeus** [custom-components/custom_updater#117]
_Before you have a reaction to this make sure you read the whole thing._

For the past couple of weeks, it has become clear to me that this project should die.
There is a lot of confusion for users, developers and me on how this actually works and what it can and should do..
I know that something like this has the potential to be useful, but currently, due to the structure of it, any changes are like painting over a rusty car.

## My issues with it.

- The documentation is bad.
- The code itself is generally bad.
- The documentation is bad.
- The code is in need of optimization.
- The documentation is bad.
- The code is too complicated for anyone to contribute to this.
- The documentation is bad.

## Will the current version stop working?

**no**

The current version of this will still continue to work, the thing that will change are my efforts on feature development.
Bug fixes will still be added but I will not add more to it.

## What now?

The only thing that makes sense is for me to stop development of it, and rather start over with something new.
For that I need **your** help, I have a general idea of what but that is me, I do not know what you (as a user or developer) what/need it to do.

This is the time for you to help decide!.

The first thing I want to change is the name, when this project started it was simple, it updated your custom components and that was it, now it does that and much more.

I have landed on HACS (Home Assistant Community Store) for now, since I believe that cover more of what it actually does.

If you have ideas on what you like it to do, please open an "issue" here https://github.com/custom-components/hacs/issues (I need input from both users and developers to do this)

All ideas will be considered.

The general idea is to take how [`custom_updater`](https://github.com/custom-components/custom_updater) and [`custom-component-store`](https://github.com/ludeeus/custom-component-store) work today with inspiration from hassio add-ons, and make a new awesome framework.

_Until the new project (codename HACS) have an MVP, I will still continue to support this with bug fixes, it is only new features that I will stop adding._

**Comment by GaryOkie** [comment]
Uh oh,  I hope my enhancement request to remove some wording confusion in custom_updater wasn't the final nail in the rusty car coffin.   (Seeing as the 2 "issues" were posted the same day).

For me, custom_updater was the most useful in simply alerting me there was an update available and to provide a quick link to the release notes.    The automatic update process was icing on the cake.

I can live with continuing to do manual updates of custom components.  It's relatively easy.     The problem is keeping up with new updates.   The only alternative I know of is to subscribe to notifications on Github for each custom component and that gets me a lot of extra junk email that I don't want.

Thanks very much for continuing to support the updater until such time there is a replacement notifier and/or updater.

**Comment by ludeeus** [comment]
@GaryOkie I started writing this issue a couple of days before actually posting it ;)

> I can live with continuing to do manual updates of custom components.

There is no need, this will continue to work until a replacement is ready (and probably some time after that as well)

**Comment by jwelter1971** [comment]
Ideally this actually should replace the updater component as a mainline component.  It does much more and actually keeps things updated....

Then we just need a corresponding Lovelace card to manage the interaction with this component.

**Comment by ludeeus** [comment]
As stated in #123 having this monitor/manage core elements is not a good option :/

There is a currently LL card, with the new component I'm thinking of using custom-panel instead to make the experience more like the hassio store.

**Comment by GaryOkie** [comment]
@ludeeus - I think having an experience "more like the hassio store" is a good approach.    To me, even better would be to have the hassio panel fully integrated with custom components (and cards) so there truly is just one place to look for updates.    Maybe the core team  would add an include for the custom updater js (if one exists) for inclusion in this panel?   

The other update that would be really nice is if the Notification Bell on the home page would flag if there were updates available - of any kind (core, add-ons, custom stuff).   Currently, it doesn't notify you of any updates.

Here's a mockup for Hassio .    For non-Hassio users, an equivalent  custom panel as you suggested could look very much the same, but without add-ons or the hassio update alert.

![hassio_panel](https://user-images.githubusercontent.com/37629938/54381312-7034fd80-465b-11e9-8d21-85fb7811f41d.JPG)

**Comment by GaryOkie** [comment]
@ludeeus - regarding my previous post above - I know you have repeatedly stated that your custom_updater, whichever form it eventually takes, can not include HA core components or OS updates.   I understand that, and agree with you if this custom updater has to be developed and maintained  fully outside of the core product as a custom or community effort.

What my example above was attempting to show is the desire for the core product to have hooks to be able to include custom components to have a cohesive UI.   

It's even a bit more disjointed than I thought.   I just noticed under the hassio system tab there was  yet another location to look for an update.  I had no idea there was an "Update" pending for HassOS!

I've visited this system tab many times and have never noticed the Update link before. 
  
![hassos_update](https://user-images.githubusercontent.com/37629938/54389845-14746f80-466f-11e9-95d4-a76a97b450ea.jpg)

**Comment by ludeeus** [comment]
I don't think this will be possible for two reasons it is a custom solution and IMO custom elements should not change how HA itself (or hassio in this case) works, and not every install are hassio.

But yes that first screenshot are in the ballpark of what I have in mind.

The Update button on the system tab, is for HassOS (OS updates) AFAIK it will only display if there is an update,

**Comment by ludeeus** [comment]
The initial version of HACS have now been released https://github.com/custom-components/hacs/releases/tag/0.1.0
