### ISSUE TITLE
HassIO v0.89.0 issue

### ISSUE THREAD

**Issue by MightyMilster** [custom-components/custom_updater#120]
Hi Joakim. After updating HA to v0.89.0 (v0.90.0 incorrectly entered originally) it seems custom updater stops working. I've been wondering if the recent stricter enforcement of component directory paths would change the way your component should be installed. Currently I have my **custom_updater.py** in the root of the **custom-components** folder. Does it need to be in it's own folder now perhaps? Thanks again for your awesome component. Best. Milster

**Comment by ludeeus** [comment]
0.90.0 does not exist yet? Are you from the future? :O

I don't think there are any changes needed for that version, but I would not know that untill the beta for it are available sometime next week.

Also please fill out the issue template.

**Comment by MightyMilster** [comment]
My apologies... v0.89.0

I am using the latest version of tracker card and custom updater. When I click on CHECK, I no longer get a service called pop-up.

**Comment by ludeeus** [comment]
That are remove in homeassistant, it will only display if something fails

**Comment by MightyMilster** [comment]
I just tested and it updated one of my cards. Thank you!

**Comment by adrianmihalko** [comment]
ludeeus:

<img width="545" alt="Screenshot 2019-03-14 at 19 48 57" src="https://user-images.githubusercontent.com/733361/54383399-4519d080-4692-11e9-838e-165e5b1fa682.png">

I click on Update all and nothing happens, there is no error in home assistant log file.

I also miss the small popup for feedback.

**Comment by MightyMilster** [comment]
Same here. If you were to check the code, it has in fact updated. I think
you need to restart Hass to load the new features of an updated component.
One you have restarted you will see that the tracker card reports
correctly.

So maybe this lack of feedback from the card is by design? I wonder whether
the red text should swap to the current column? To show that the component
code has been updated, but a restart/load has not been performed.

**Comment by adrianmihalko** [comment]
" I wonder whether
the red text should swap to the current column? To show that the component
code has been updated, but a restart/load has not been performed."

This is how it worked in the past versions.
