### ISSUE TITLE
Show HA version and if update available

### ISSUE THREAD

**Issue by jwelter1971** [custom-components/custom_updater#123]
As this component has become the update hub it would be nice if it would optionally show the HA version and if an update is available. Would eliminate duplicate areas showing this information.

**Comment by GaryOkie** [comment]
Not a bad idea, but FYI - if you use HASS.IO, the dashboard section is also an "update hub" for all the add-ons you may have installed.      The system section is another place you need to look for hassio system updates.    So - three different places to look to see if there are any updates available - not counting Github/forum notices about custom components that aren't configured to use this custom_updater.

**Comment by ludeeus** [comment]
This should not be used to track and potentially update official elements like HA itself.
If I open for that, soon people want it for their addons, OS packages, you name it.

This should be locked to custom HA resources.

To track the version of HA you can use this https://www.home-assistant.io/components/sensor.version/
To upgrade use https://www.home-assistant.io/docs/installation/updating/
