### ISSUE TITLE
[FR] Allow caching, but use If-Modified-Since header

### ISSUE THREAD

**Issue by randellhodges** [custom-components/custom_updater#125]
## Describe the solution you'd like

Either an enhancement to the customcards or another endpoint.

When serving the file, remove the cache/expires headers and add in the If-Modified-Since header. I will try it out locally and see how well it works.

**Comment by ludeeus** [comment]
I have tried this in the past with little luck :/

**Comment by randellhodges** [comment]
I'll play around with the idea and if something sticks, I'll post back :)

**Comment by randellhodges** [comment]
Changing the following seems to be all that is needed for Chrome. I haven't tried other browsers.

```
            resp.headers["Cache-Control"] = "max-age=0, must-revalidate"
            #resp.headers["Cache-Control"] = "no-store, no-cache, must-revalidate"
            #resp.headers["Pragma"] = "no-cache"
            #resp.headers["Expires"] = "0"
```

I verified that the first time, I get a 200 with that Cache-Control and Last-Modified header in the result. Refreshing the browser I see the 304 response, so it looks like aiohttp.web is handling the 304 as long as the browswer sends If-Modified-Since header.

I had to use `max-age=0, must-revalidate` to get Chrome to send `If-Modified-Since`

I am no expert on caching so I'm not certain where this would fall apart. Worse case, the end user would need to clear their cache.

**Comment by ludeeus** [comment]
Want to make a PR for this?

**Comment by randellhodges** [comment]
> Want to make a PR for this?

Sure. It'll have to be later tonight or tomorrow, but I'll submit one.
