### ISSUE TITLE
README URL fix?

### ISSUE THREAD

**Issue by jschwalbe** [custom-components/custom_updater#129]
Might I suggest that in the README you change the URL to the 'raw' version of the file, https://raw.githubusercontent.com/custom-components/custom_updater/master/custom_components/custom_updater.py so that it can be linked and downloaded quicker? The way it's in the README right now looks like it should be wget'able, but it's not. 

(Super small issue but figured it might save someone 3 minutes of troubleshooting? I didn't think to look at the file at first, since the README said HA would have issues with the config.]

**Comment by ludeeus** [comment]
I guess you meant the wiki, updated now.
