### ISSUE TITLE
Custom Cards not updating since 0.91.x

### ISSUE THREAD

**Issue by DavidFW1960** [custom-components/custom_updater#130]
## Version of the custom_component

4.2.19
## Describe the bug
Custom updater stopped working today after 0.91.1

EDIT: it's actually this file https://raw.githubusercontent.com/custom-cards/information/master/repos.json has not been updated
## `custom_updater` configuration

```yaml

# Add configuration here

```

## Resources in lovelace configuration

```yaml

# Add configuration here

```

## Tracker-card configuration

```yaml

# Add configuration here

```

## Debug log

```text

Add your logs here.
I’m not seeing anything in the logs. I know the compact_custom_header was updated today and another card as well but neither are showing an available update.

```

**Comment by ludeeus** [comment]
Thanks for reporting.
One of my docker hosts did not start properly after a maintenance job.
That particular hos is running this <https://github.com/ludeeus/tasks/blob/ca57eef758dbfe7b5bbd197881227348061498bd/rootfs/etc/services.d/hourly/run#L12> which handles updates of that file.
this have now been corrected <https://github.com/custom-cards/information/commit/4b4cdee6450c521e23b602cbceb92295612a065f>
