### ISSUE TITLE
Custom Updater does not show components

### ISSUE THREAD

**Issue by bigred10151990** [custom-components/custom_updater#132]
## Version of the custom_component
4.2.19

## Describe the bug
Custom updater does not show any components other than custom_updater

## `custom_updater` configuration

custom_updater:
   
  component_urls: !include_dir_merge_named ../custom_updater/component_urls

  card_urls: !include_dir_merge_named ../custom_updater/card_urls

# Add configuration here

i'm using a package type setup where the folder listed above contains a single yaml file for each url. the files themselves are just the url.

I have also tried adding the url directly to the  component_urls: section and have the same results

## Resources in lovelace configuration

resources:
  - type: module
    url: /local/surveillance-card.js?track=true
  - type: js
    url: /local/vertical-stack-in-card.js?track=true
  - type: js
    url: /local/card-tools.js?track=true
  - type: module
    url: /local/secondaryinfo-entity-row.js?track=true
  - type: js
    url: /local/list-card.js?track=true
  - type: module
    url: /local/button-card.js?track=true
  - type: module
    url: /customcards/github/custom-cards/tracker-card.js?track=true
  - type: js
    url: /local/ext-weblink.js?track=true
  - type: module
    url: /local/mini-media-player-bundle.js?track=true
  - type: module
    url: /customcards/github/maykar/compact-custom-header.js?track=true
  - type: module
    url: /local/button-card.js?track=true

# Add configuration here

```

## Tracker-card configuration

type: 'custom:tracker-card'

# Add configuration here

```

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
As described in the issue template issues missing required information will be closed.
In this issue these are missing:

- Debug logs
- Proper Component Configuration
