### ISSUE TITLE
VOTE: Change the structure.

### ISSUE THREAD

**Issue by ludeeus** [custom-components/custom_updater#133]
_Spin-off from https://github.com/custom-components/custom_updater/issues/131_

## Issue:

```text
Unable to find services.yaml for the custom_updater integration
```

This component is just a single file directly in the `custom_components` dir.
To comply with recent changes this would need to change into something like [blueprint](https://github.com/custom-components/blueprint)

### Add your vote as a reaction to this:
👍  Change the structure of this component (This **WILL** be a breaking change.)
👎  Leave it, it's just a warning. 
👀  No opinion.

_I'll leave this open until Sunday and will do the action based of the result then._

**Comment by DavidFW1960** [comment]
So my opinion is that it should follow the structure for custom components and if that’s a breaking change so be it... I assume it’s not possible for both approaches to coexist? Probably whatever you do you’re going to upset someone. It seems that eventually this change will be forced anyway? If so I’d prefer to have my pain now....
Thanks for the explanation anyway. I’m good with whatever you decide even though I’d like to get rid of the warning.

**Comment by ludeeus** [comment]
I don't see a reason for this to be forced, but I have been wrong before.
There can certainly be more than one "styles" of this, but I will only support one, and that is this one.
Or the upcoming [HACS](https://github.com/custom-components/hacs) if I ever get the time to finish that.

**Comment by stepanov1975** [comment]
I think it will be better if everyone will aline with the recommended style. Chaos usually not a good thing.

**Comment by ludeeus** [comment]
So I guess folks really like breaking changes 🤷‍♂️ 
![image](https://user-images.githubusercontent.com/15093472/56785703-9f13c700-67f6-11e9-9204-db143e76111e.png)
Will get started on that when some time free up, probably not until Sunday/Monday (UTC)

**Comment by stepanov1975** [comment]
We like order :)

**Comment by DavidFW1960** [comment]
Hahahahaha!!!! No ambiguity there is there. Lol.

**Comment by rpitera** [comment]
Honestly, whatever keeps this component going I will do.  I can't imagine life without it.
