### ISSUE TITLE
Hassio pyupdate failed 

### ISSUE THREAD

**Issue by P2mb2** [custom-components/custom_updater#142]
Hi, 

i'm running home assistant 0.92.2 on hassio pi3 installation. 
Somehow i'm unable to install the pyupdate dependency... it seams an sll/connectivity error... any help fixing this ?

logs:

> 2019-05-16 11:27:31 ERROR (SyncWorker_15) [homeassistant.util.package] Unable to install package pyupdate==1.4.0: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')"))': /simple/pyupdate/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')"))': /simple/pyupdate/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')"))': /simple/pyupdate/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')"))': /simple/pyupdate/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')"))': /simple/pyupdate/
  Could not find a version that satisfies the requirement pyupdate==1.4.0 (from versions: )
No matching distribution found for pyupdate==1.4.0
2019-05-16 11:27:31 ERROR (MainThread) [homeassistant.requirements] Not initializing custom_updater because could not install requirement pyupdate==1.4.0
2019-05-16 11:27:31 ERROR (MainThread) [homeassistant.setup] Setup failed for custom_updater: Could not install all requirements.

**Comment by ludeeus** [comment]
It's out of my hands, probably an issue with DNS (locally) or pypi (remote) try again later

**Comment by P2mb2** [comment]
Hi ludeeus, 

thanks ;) i restarted and try several times... it worked. 

;)
