### ISSUE TITLE
Help - install issue and card display: Custom element doesn't exist: tracker-card.

### ISSUE THREAD

**Issue by jamiepryer** [custom-components/custom_updater#143]
## Version of the custom_component
latest version, as found here today: https://github.com/custom-components/custom_updater
Hassio = 0.93.1

## Describe the bug
I get this error:

> Custom element doesn't exist: tracker-card.
> {
>   "type": "custom:tracker-card"
> }

I have uploaded _init.py and services.yaml to: 
**\\HASSIO\config\custom_components\custom_updater**

i have uploaded **tracker-card.js** to:
**\\HASSIO\config\www\customcards\**

rebooted Hassio twice.

## `custom_updater` configuration
```yaml
custom_updater: 

## Resources in lovelace configuration
```yaml
  - url: /customcards/tracker-card.js?track=true
    type: module



## Tracker-card configuration

```yaml

# Add configuration here
```
type: 'custom:tracker-card'

## Debug log

```text

Log Details (ERROR)
Wed May 22 2019 12:30:00 GMT+0100 (British Summer Time)
Error during template condition: UndefinedError: 'None' has no attribute 'attributes'

2019-05-22 12:30:00 ERROR (MainThread) [homeassistant.helpers.condition] Error during template condition: UndefinedError: 'None' has no attribute 'attributes'
2019-05-22 12:30:00 ERROR (MainThread) [homeassistant.helpers.condition] Error during template condition: UndefinedError: 'None' has no attribute 'attributes'
```

**Comment by ludeeus** [comment]
As described in the issue template issues missing required information will be closed.
In this issue these are missing:

- Component version (latest is not a version)
- Debug logs
