### ISSUE TITLE
customer_updater 5.1.0 available, but "Update All" does nothing

### ISSUE THREAD

**Issue by garnern2** [custom-components/custom_updater#144]
My tracker card is showing 5.1.0 available, but from what I see on GitHub, only 5.0.0 is available. 5.0.0 is the version I currently have installed. I see no errors of any kind in the logs even after I click "Update All" on the tracker card and nothing happens. Please advise.

**Comment by proddy** [comment]
I have the same issue

**Comment by ludeeus** [comment]
As described in the issue template issues missing required information will be closed.
In this issue these are missing:

- Component version
- Debug logs
- Component configuration
- Lovelace configuration
- Proper description

**Comment by garnern2** [comment]
If you’re going to be this anal about closing things, at least correctly list the claimed “missing information,” even if it is irrelevant. 

I specifically listed the component version.

**Comment by ludeeus** [comment]
You got me there! You had that one.

But reporting an issue without _any_ useful information is the same as not reporting it in the first place.
The template is there for a reason, everything there is required for me to even start to understand what the issue might be.

Feel free to open a new issue (where you follow the provided template) and I will have a look.
