### ISSUE TITLE
No support for multi resource cards

### ISSUE THREAD

**Issue by jpcaldwell30** [custom-components/custom_updater#15]
Currently only supports one "remote_location" entry for a cards js file. I have a custom card that has both a .js file and a .lib.js Can support be added for cards that have more than one resource file? Here is the repo of the card in question. https://github.com/ciotlosm/custom-lovelace/tree/master/thermostat-card

**Comment by ludeeus** [comment]
@jpcaldwell30 I will try to add support for this in the next version 👍

**Comment by ludeeus** [comment]
This was added in https://github.com/custom-components/custom_updater/releases/tag/2.2.0
