### ISSUE TITLE
hide_sensor not respected.

### ISSUE THREAD

**Issue by tjorim** [custom-components/custom_updater#17]
**Version of the cusom_component**

2.2.0

**Configuration snippet**
``` yaml
custom_updater:
  hide_sensor: true
```

**Describe the bug**
Just did a clean install of my HA. Placed custom_updater.py in custom_components, tracker-card.js in www. After a restart I got some errors, probably related to there being no ui-lovelace.yaml yet. I created a lovelace file, but didn't include the tracker-card yet. After one more restart, I noticed a sensor at the top of the dashboard as seen below:
![image](https://user-images.githubusercontent.com/1294876/44416878-75721400-a574-11e8-8581-41fa79d9c9b9.png)
Viewing the current entities list, I noticed there being only `hidden: true` value for the component-tracker, not for custom-cards-tracker, which might be related.
![image](https://user-images.githubusercontent.com/1294876/44416862-68edbb80-a574-11e8-9de4-a5d67a9be5a8.png)

**Comment by ludeeus** [comment]
Both actually have the same bug (if they have no cards/component to track)

**Comment by ludeeus** [comment]
Corrected in <https://github.com/custom-components/custom_updater/releases/tag/2.5.0>
