### ISSUE TITLE
Error message bug

### ISSUE THREAD

**Issue by pnbruckner** [custom-components/custom_updater#18]
**Version of the cusom_component**

2.2.0

**Describe the bug**
When using component_urls, if one of those doesn't work, the error message lists the default URL. I didn't try it, but the same bug appears to affect card_urls, too.

**log**

```
2018-09-07 13:08:17 DEBUG (Thread-5) [custom_components.custom_updater] Could not get remote info for url https://raw.githubusercontent.com/custom-components/information/master/repos.json
```

**Comment by pnbruckner** [comment]
The problem is here:

https://github.com/custom-components/custom_updater/blob/289b58041c72b2098d480cfd77f9c2f4b27ca9fe/custom_components/custom_updater.py#L436

`DEFAULT_REMOTE_COMPONENT_CONFIG_URL` should be `url`.

It would appear the same problem is here, too:

https://github.com/custom-components/custom_updater/blob/289b58041c72b2098d480cfd77f9c2f4b27ca9fe/custom_components/custom_updater.py#L296

**Comment by ludeeus** [comment]
@pnbruckner Thanks for reporting, a fix for it is live now :)
<https://github.com/custom-components/custom_updater/releases/tag/2.2.1>
