### ISSUE TITLE
Getting Errors Not Finding Components Not Installed

### ISSUE THREAD

**Issue by techwithjake** [custom-components/custom_updater#25]
**Version of the custom_component** 
**2.7**

**Describe the bug**
On boot, customer updater is throwing errors about not finding components that aren't installed.

**log**

```
2018-09-21 17:29:01 DEBUG (SyncWorker_2) [custom_components.custom_updater] Could not get the local version for sensor.syncthing
```

I don't have Syncthing Sensor installed. The custom updater shouldn't care that it can't find it since it's not installed.

**Comment by ludeeus** [comment]
This is the expected behavior.
This is not an error but a DEBUG message.

"The custom updater shouldn't care that it can't find it since it's not installed." It does not and that is what the message are saying.
