### ISSUE TITLE
Add support for python_scripts

### ISSUE THREAD

**Issue by pnbruckner** [custom-components/custom_updater#29]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Allow JSON files to list files in the python_scripts folder. That would allow controlled releases of these, too.

**Describe alternatives you've considered**
None.

**Additional context**
I think this could fairly easily be made to work by changing CustomComponents.install() to use `self.hass.data[COMP_DATA][component]['local']` (i.e., the directory part of it) instead of `component` when determining which folder to check/create.

**Comment by ludeeus** [comment]
@pnbruckner Got any examples for python_scripts that could be used?

**Comment by pnbruckner** [comment]
https://github.com/pnbruckner/homeassistant-config/blob/master/python_scripts/light_store.py, _after_ I add `__version__`.

**Comment by pnbruckner** [comment]
FWIW, here's the [community forum topic](https://community.home-assistant.io/t/python-script-to-save-and-restore-switches-and-lights) where it's discussed.

**Comment by ludeeus** [comment]
@pnbruckner I'm working on implementing this now, can you add __version__ to the script and create a json file that I can test with?

**Comment by pnbruckner** [comment]
I added the version to the script on my master branch, then updated my json file on a branch for now. I used 'python_scripts.light_store' for the name. The json file is here: https://raw.githubusercontent.com/pnbruckner/homeassistant-config/python_scripts/custom_components.json

**Comment by pnbruckner** [comment]
Actually I think the name should be python_script.light_store, since the domain is python_script, even though it goes in the python_scripts folder. I'll change the .json file accordingly.

**Comment by ludeeus** [comment]
I would need a seperate json file, but it's enough for me to experiment with ;)

**Comment by ludeeus** [comment]
Support for python_script are now added on the latest version 3.0.0
example config:
```
custom_updater:
  track:
    - components
    - python_scripts
  python_script_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/d550416d74e8e1f1ea7e2d8df4782b2c9da16c80/python_scripts.json

```

**Comment by ludeeus** [comment]
<https://github.com/custom-components/custom_updater/wiki/python_scripts>
