### ISSUE TITLE
Impossible to customize sensors created by CC  Custom Updater

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-components/custom_updater#35]
`show_last_changed` are not an option of this component.

_Originally posted by @ludeeus in https://github.com/custom-components/custom_updater/issues/22#issuecomment-425749276_

please see: 

https://github.com/custom-components/custom_updater/issues/22#issuecomment-425700318

and

https://community.home-assistant.io/t/customize-custom-updater-sensors-impossible/70974

We cant customize the sensors created by this CC, which is rather unusual, and please check why this is, and preferably, change code to make it possible.

with Custom-ui installed we should be able to do this:

```
homessistant:
  customize:
    sensor.custom_card_tracker:
   # icon: mdi:cloud-search
    friendly_name: Custom card tracker
    show_last_changed: true
    templates:
      icon: >
        if (state === 0) return 'mdi:cloud-search';
        return 'mdi:cloud-upload';
      icon_color: >
        if (state === 0) return 'grey';
        return 'rgb(251, 210, 41)';
```

**Comment by ludeeus** [comment]
If you find out what it takes I''ll be happy to include it.
But I have never used custom-ui (Do not use HA at all now, and when I did I did not use the UI)

**Comment by Mariusthvdb** [comment]
cool!

for me, I always use show_last_changed: and friendly_name:

adding to that, templates for icon: and icon_color: based on the state, or in this case, based ni the state of another entity.

I've created template_sensors based on your sensors for the time being now, with the above, like this:

```
sensor:
  platform: template
  sensors:
        custom_card_tracker_template:
        friendly_name: Custom card tracker
        value_template: >
          {{states('sensor.custom_card_tracker')}}
        icon_template: >
          {% if states('sensor.custom_card_tracker')|int == 0 %}mdi:cloud-search
          {% else %} mdi:cloud-upload
          {% endif %}

      custom_component_tracker_template:
        friendly_name: Custom component tracker
        value_template: >
          {{states('sensor.custom_component_tracker')}}
        icon_template: >
          {% if states('sensor.custom_component_tracker')|int == 0 %}mdi:cloud-search
          {% else %} mdi:cloud-upload
          {% endif %}
```

and, because show_last_changed and icon_color are not available in the regular template sensors, I customize these sensors like this ([using @andrey s custom-ui](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/templates.md)):

```
homeassistant:
  customize:
    sensor.custom_card_tracker_template:
      show_last_changed: true
      templates:
        icon_color: >
          if (state === '0') return 'grey';
          return 'rgb(251, 210, 41)';
    sensor.custom_component_tracker_template:
      show_last_changed: true
      templates:
        icon_color: >
          if (state === '0') return 'grey';
          return 'rgb(251, 210, 41)';

```

![schermafbeelding 2018-09-30 om 23 42 51](https://user-images.githubusercontent.com/33354141/46263081-d3e2c880-c50a-11e8-98f0-39cd88469fde.jpg)
![schermafbeelding 2018-09-30 om 23 43 51](https://user-images.githubusercontent.com/33354141/46263082-d3e2c880-c50a-11e8-9edf-ecbef46b883c.jpg)

vs:

![schermafbeelding 2018-09-30 om 23 45 13](https://user-images.githubusercontent.com/33354141/46263091-e9f08900-c50a-11e8-9dbf-1caaaed4e526.jpg)


If you could make the above possible directly from the sensor that would be magic. If not, please enable the option for customizing so these templates sensors aren't necessary (I wouldn't know how, but as it stands we can't, and thats a first for me..)

thanks for considering!

**Comment by ludeeus** [comment]
I get the idea behind this, bu I have no idea on how to add this inn.
There is nothing like what you are presenting to me that helps.

Maybe if someone sees your forum post or this issue, that know what needs to be there.

Another possibility would be for me to invest time to setup custom UI, but that will have an low priority.
Sorry about that.

**Comment by Mariusthvdb** [comment]
> I get the idea behind this, but I have no idea on how to add this inn.

If you cant 'add it in' maybe just prevent the output sensors from being fixed in their representation in the frontend. There must be some code preventing to change the way they are displayed right now.

might help: Hue.py by @robmarkcole sets several icons in the python itself, but we are able to override these and change in the HA frontend by customizing.

Please have a look why this is, and what could be the reason?

**Comment by ludeeus** [comment]
Most likely this is due to the fact that they are not "real" sensors, just hass.set.state calls

**Comment by Mariusthvdb** [comment]
That might well be the case. I have a set of sensors like that, and customize these as follows:

```
hass.states.set('sensor.family_home', count_home, {
    'custom_ui_state_card': 'state-card-custom-ui',
    'friendly_name': 'Family Home?',
    'home': ', '.join(home),
    'away': ', '.join(away),
    'icon': whichIcon,
    'count_home': count_home,
    'count_away': count_away,
    'family_count': familyCount,
    'icon_color': icon_color ,
    'show_last_changed': 'true'
     })
```

Ive tried to do this in your code, but think I haven found the correct spot to do that....

HUe.py creates true sensors like this:

```
class HueSensor(Entity):
    """Class to hold Hue Sensor basic info."""

    ICON = 'mdi:run-fast'

    def __init__(self, hue_id, data):
        """Initialize the sensor object."""
        self._hue_id = hue_id
        self._data = data    # data is in .data
        self._icon = None
        self._name = self._data.data[self._hue_id]['name']
        self._model = self._data.data[self._hue_id]['model']
        self._state = self._data.data[self._hue_id]['state']
        self._attributes = {}
```

wouldn't that be an option in your CC?

**Comment by ludeeus** [comment]
> Ive tried to do this in your code, but think I haven found the correct spot to do that....
It's in multiple places.

> wouldn't that be an option in your CC?

Maybe.. usually that require a seperate file for the sensor, I tried that with this component earlier, I was too confusing for the user, if I can create a proper sensor from the same file that should work.

**Comment by iantrich** [comment]
@Mariusthvdb I think a custom card is the answer to what you want within Lovelace.

**Comment by ludeeus** [comment]
@iantrich True, but for non-lovelace users this is still a valid request :)

**Comment by Mariusthvdb** [comment]
> @iantrich True, but for non-lovelace users this is still a valid request :)

since this is a valid request, please don't close, but solve...

**Comment by ludeeus** [comment]
Bot is trying to "help"

**Comment by ludeeus** [comment]
@Mariusthvdb The only good way of achieving this will be to have it add a sensor object.

**Comment by Mariusthvdb** [comment]
Hi Yes probably.
Will that be something you can do in the components code?

**Comment by ludeeus** [comment]
I'm sorry but I will not implement this.
If anyone wants to create a PR for it, I'll be happy to accept it.
