### ISSUE TITLE
Feature Suggestion: Home Assistant update availability

### ISSUE THREAD

**Issue by jpcaldwell30** [custom-components/custom_updater#36]
**Is your feature request related to a problem? Please describe.**
When using Lovelace, there isn't any clear indicator for when an HA update/new version is availible. In the non Lovelace view, there is a sensor that will show up when a new update is availible. 
**Describe the solution you'd like**
I'd like to use custom updater as a substitution for this sensor while using lovelace. It would also have the added benefit of keeping all updating/versioning in one place.

**Comment by ludeeus** [comment]
Thanks for this, but this is really out of the scope of this component, but I have another sensor you might be interested in:
<https://github.com/custom-components/sensor.versions>
