### ISSUE TITLE
Sensors are no longer hidden even though configuration is applied

### ISSUE THREAD

**Issue by collse** [custom-components/custom_updater#47]
**Version of the custom_component**
tracker_card 0.1.5 / custom_updater 3.1.6

**Describe the bug**
The configuration below, doesnt hide the sensors in the ui no more
>custom_updater:
  show_installable: True
  hide_sensor: True
  track:
    - components
    - cards
    - python_scripts

indenting is correct - just doesnt show here ...

instead it shows the sensors for all three trackers
**log**
unfortunately this doesn't produce any logs
```

**Comment by ludeeus** [comment]
<https://github.com/custom-components/custom_updater/releases/tag/3.1.7>
