### ISSUE TITLE
SyntaxError: EOL while scanning string literal

### ISSUE THREAD

**Issue by timelf123** [custom-components/custom_updater#65]
**Version of the custom_component**
latest on 0.84
**Describe the bug**
`SyntaxError: EOL while scanning string literal`
Fatal error when config checking

**log**
https://i.imgur.com/8gcsgqr.png
```
SyntaxError: EOL while scanning string literal
```

**Comment by ludeeus** [comment]
It looks like your local file is broken, try downloading it again

**Comment by timelf123** [comment]
`core-ssh:/config/custom_components# wget https://raw.githubusercontent.com/custom-components/custom_updater/master/custom_components/custom_updater.py`

**Comment by timelf123** [comment]
This solved it and you were right, thanks

```
core-ssh:/config/custom_components# wget https://raw.githubusercontent.com/custom-components/custom_updater/master/custom_components/custom_updater.py
```
