### ISSUE TITLE
Question: Notification on available update

### ISSUE THREAD

**Issue by h4nc** [custom-components/custom_updater#68]
Do you have an example on how to get a notification when an update comes available?

**Comment by ludeeus** [comment]
If produces sensors with attributes you can listen for changes in.
You can look for changes in the state, and use the `has_update` attribute in a notification to list components/cards with updates.

To read about this look at the official automation docs https://www.home-assistant.io/docs/automation/

**Comment by h4nc** [comment]
It looks like this.
Will the global "has_update" change when one of the cards/components have an update available? Or only has_update for the specific card/component

```
domain: custom_cards
has_update: ### will this get a state?
monster-card: {
  "local": "0.2.3",
  "remote": "0.2.3",
  "has_update": false,
  "not_local": false,
  "repo": "https://github.com/ciotlosm/custom-lovelace/tree/master/monster-card",
  "change_log": "https://github.com/ciotlosm/custom-lovelace/tree/master/monster-card/changelog.md"
}
tracker-card: {
  "local": "0.1.5",
  "remote": "0.1.5",
  "has_update": false,
  "not_local": false,
  "repo": "https://github.com/custom-cards/tracker-card",
  "change_log": "https://github.com/custom-cards/tracker-card"
}
hidden: false
```

**Comment by ludeeus** [comment]
`has_update` is a list of cards or components (depending on the sensor) that has pending updates.
in your case, this can potentially be `has_update: ['monster-card', 'tracker-card']`

**Comment by h4nc** [comment]
How can I extract this information to a simple binary sensor. I don't like to know which component has an updata available, I'd like to know if there is any update available.

So if the list is empty: false
Something in the list: true.

With this I can trigger an automation to send a persistant notification.

**Comment by ludeeus** [comment]
These questions are more suited for the support channels for Home Assistant since this is basic functionality.

```
"{{ not state_attr('sensor.sensorname', 'has_update'  }}"
```
_should_ give you this.

**Comment by h4nc** [comment]
Ok, thank you!

**Comment by h4nc** [comment]
this works:

{{ states.sensor.custom_component_tracker.attributes.has_update == [] }}
