### ISSUE TITLE
"Update all" removes the group of the ui-lovelace.yaml file

### ISSUE THREAD

**Issue by nicop4** [custom-components/custom_updater#69]
**Version**
3.1.8

**Description of the bug**
When I hit "update all" button everything is updated as expected but the linux group of the `ui-lovelace.yaml` file is removed. It appears as `nogroup`.

I set write access rights to the homeassistant group for this file because the user I'm connected with does modifications to the file. So each time I update I have to re-set the group.
The rights are still there though.

Is this possible for the tracker card to not change the group ? 

<img width="654" alt="image" src="https://user-images.githubusercontent.com/10168765/51270161-85c3d900-19c4-11e9-9121-0578f0f7e7a0.png">

**Comment by ludeeus** [comment]
@nicop4 I just tested this (with the newest version) and do not see this issue.

Does the parent folder have `nogroup`?

**Comment by ludeeus** [comment]
My test was with Hassbian, which is basically the same setup.

**Comment by ludeeus** [comment]
@nicop4 with the newerst version it no longer write to that file, so this should be "fixed" (not happening anymore)

**Comment by nicop4** [comment]
Hi @ludeeus, yes indeed I saw the new release and I upgraded so this sould not be an issue for me anymore. The only thing I saw and could be related is the directory pycache with `nogroup`, do you think it could have been related ? 

<img width="642" alt="image" src="https://user-images.githubusercontent.com/10168765/52899577-d872f980-31eb-11e9-9f19-05510de38ea4.png">

I have another issue though, but with the tracker card, the button are just non-clickable texts, I will take a look at that and trace it in the card repo if needed.

Thanks for your help and your work.

**Comment by ludeeus** [comment]
> The only thing I saw and could be related is the directory pycache with `nogroup`

Potentially 🤷‍♂️ 

> but with the tracker card, the button are just non-clickable texts

They are clickable, but does not give "feedback", when you upgrade to 0.88 this will change :)

**Comment by nicop4** [comment]
Ok great then I won't spend time on that, thanks for the feedback ;)
