### ISSUE TITLE
Hide 'sensor' entities

### ISSUE THREAD

**Issue by tjorim** [custom-components/custom_updater#7]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when the 'sensors' (with just some gibberish 😉) for this component (sensor.custom_card_tracker and sensor.custom_component_tracker) show up on my overview. There is currently no way to hide these via `customize.yaml`.

**Describe the solution you'd like**

In a perfect world they would adhere to how other entities behave, if this is not possible via `customize:`, provide a config option for it.

**Describe alternatives you've considered**

As @ludeeus recommended, I added two lines to `custom_updater.py`.
A new line after line 116 to hide the card sensor containing:
```python
self.hass.data[CARD_DATA]['hidden'] = True
```
and a new line after line 252 to hide the component sensor containing:
```python
self.hass.data[COMPONENT_DATA]['hidden'] = True
```
This does effectively hide the entities in the overview.

**Additional context**

One side effect of this solution shows itself in the Lovelace UI,
the tracker-card now has extra entries for `hidden` as seen below:

![image](https://user-images.githubusercontent.com/1294876/43471269-de3f553c-94ea-11e8-963a-721d428d9d9f.png)

**Comment by ludeeus** [comment]
This is added in https://github.com/custom-components/custom_updater/pull/8
```
custom_updater:
  hide_sensor: True
```
