### ISSUE TITLE
please add individual update (opposed to update all)

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-components/custom_updater#71]
**Is your feature request related to a problem? Please describe.**

Now available updates for several custom cards only work for HA 86.+ and I am still and will be for a longer time on 84.3, I don't want to use, or can't use, update-all without rendering my system with a lot of issues and errors. Maybe even useless because of the continuous script errors.

**Describe the solution you'd like**

please add a way to update individual cards (or a way t exclude cards from the update-all)

**Describe alternatives you've considered**

see above for 2 possible options

**Additional context**

see @thomasloven 's release note: https://community.home-assistant.io/t/my-lovelace-plugins/70726/665?u=mariusthvdb
see below for the offending cards, that have an update now, and conflict with my HA version .

![schermafbeelding 2019-01-24 om 10 32 08](https://user-images.githubusercontent.com/33354141/51668822-53693b80-1fc3-11e9-8cc7-93975fa53fbe.jpg)

**Comment by ludeeus** [comment]
You can use the service `custom_updater.install` to update a single card

**Comment by ludeeus** [comment]
I see... I thought you were talking about the component since you opened the issue here :)

This should be opened in this repo instead <https://github.com/custom-cards/tracker-card> :)
_I can't move it there_

**Comment by Mariusthvdb** [comment]
consider it done: https://github.com/custom-cards/tracker-card/issues/31
