### ISSUE TITLE
Cards don't show as installed

### ISSUE THREAD

**Issue by tyfoon** [custom-components/custom_updater#80]
**Version of the custom_component**

4.0.0

**Describe the bug**
I have tracker_card and custom_updater component installed. Running last version (4) of custom_updater. Running lovelace in storage all custom cards work fine

Issue:
For some reason the tracker/custom_updater does not see that I have custom cards installed (however does see this for customer components). 

Best described (incl screenshots) here: https://community.home-assistant.io/t/custom-updater-and-tracker-card-not-reporting-correctly/70949/64

**log**

```
Add your logs here.
```

**Comment by ludeeus** [comment]
For components there is a version tag inside the files, for cards this is not the case, so we can only make assumptions of the local "version".

Version 4 of this got a new version control logic for cards.

This was mentioned in the release notes:

```
The first time you use this version it will not know the local version of your cards, click the UPDATE ALL button to correct this.
```
<https://github.com/custom-components/custom_updater/releases/tag/4.0.0>
Did you click that button?

**Comment by tyfoon** [comment]
Well, stupid me! Guess I missed that. All works fine now. Thanks
