### ISSUE TITLE
Can't see the custom_component and custom_python_scripts

### ISSUE THREAD

**Issue by BartEngelen** [custom-components/custom_updater#81]
**Version of the custom_component**
Latest version (4.0.0)

**Describe the bug**
Installed and configured the latest version
I don't see my installed custom_components and custom_python_scripts in the sensor.custom_component_tracker and sensor.custom_python_script_tracker.

The sensor.custom_card_tracker works fine

**log**
Add your logs here.

**Comment by ludeeus** [comment]
Please add [debug logs](https://github.com/custom-components/custom_updater/wiki/Debug) and screenshots describing your issue

**Comment by BartEngelen** [comment]
configuration.yaml:
![configuration](https://user-images.githubusercontent.com/17978789/52805072-0f2eff80-3086-11e9-80c9-ddc2be49d6b6.JPG)
ui-lovelace.yaml:
![custom_cards](https://user-images.githubusercontent.com/17978789/52805094-1f46df00-3086-11e9-9b1c-3f0273fdf996.JPG)
custom_components (folder):
![custom_components](https://user-images.githubusercontent.com/17978789/52805146-41d8f800-3086-11e9-9359-c6ac6f1089d6.JPG)
UI:
![custom_components_ui](https://user-images.githubusercontent.com/17978789/52805165-49000600-3086-11e9-9e7d-1f94860dc46b.JPG)

**Comment by BartEngelen** [comment]
The log file:
[home-assistant.log](https://github.com/custom-components/custom_updater/files/2866171/home-assistant.log)

**Comment by deluxestyle** [comment]
I have the same issue

**Comment by ludeeus** [comment]
@BartEngelen @deluxestyle 
Do you actually have any trackable components/python_scripts?

**Comment by BartEngelen** [comment]
Hello, Yes I have the custom_updater component.Regards,BartVerzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Joakim Sørensen <notifications@github.com> Datum: 14/02/19  21:45  (GMT+01:00) Aan: custom-components/custom_updater <custom_updater@noreply.github.com> Cc: Bart Engelen <bart.engelen1@telenet.be>, Mention <mention@noreply.github.com> Onderwerp: Re: [custom-components/custom_updater] Can't see the custom_component and custom_python_scripts (#81) @BartEngelen @deluxestyle
Do you actually have any trackable components/python_scripts?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/custom-components/custom_updater","title":"custom-components/custom_updater","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/custom-components/custom_updater"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ludeeus in #81: @BartEngelen @deluxestyle \r\nDo you actually have any trackable components/python_scripts?"}],"action":{"name":"View Issue","url":"https://github.com/custom-components/custom_updater/issues/81#issuecomment-463788425"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/custom-components/custom_updater/issues/81#issuecomment-463788425",
"url": "https://github.com/custom-components/custom_updater/issues/81#issuecomment-463788425",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ludeeus** [comment]
@BartEngelen as stated in the README.md file and the releasenotes for `4.0.0` the `custom_updater` has been removed from it, it will be added back in later.

**Comment by ludeeus** [comment]
I'm guessing this is the only component you have too @deluxestyle ?

**Comment by deluxestyle** [comment]
Yes exactly

**Comment by ludeeus** [comment]
I will enable `custom_updater` in that list in a couple of days, if you do not track `python_script` you should both remove that from the config.
I will close this now, since it's expected that you do not see anything ATM.
