### ISSUE TITLE
Now vales after change to version 4.0.1

### ISSUE THREAD

**Issue by Obicom** [custom-components/custom_updater#83]
**Version of the custom_component**
4.1

**Describe the bug**
No values are shown after update to 4.0.1

**yaml**
> # Enable custom updater
custom_updater:
  track:
    - components
    - cards
    - python_scripts
  mode: storage
  card_urls:
    - https://raw.githubusercontent.com/sgttrs/lovelace-weather-card-chart/master/custom-updater.json
    - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-google-calendar-card/master/custom_updater.json

```
Add your logs here.
```
![image](https://user-images.githubusercontent.com/25134482/52846337-a12c1c00-3109-11e9-9ea1-d173ed967194.png)

**Comment by ludeeus** [comment]
That is expected, hit the update all button and it will be correct again

**Comment by Obicom** [comment]
Ok, that works but Custom Components are no longer listed

![image](https://user-images.githubusercontent.com/25134482/52848491-2239e200-310f-11e9-933c-185382de8939.png)

**Comment by ludeeus** [comment]
If you only have custom_updater that you track, that is also expected, it will return in a few days ;)

**Comment by Obicom** [comment]
I use more custom components but not sure if this are tracked by your component

**Comment by ludeeus** [comment]
Newer versions of rpi_power is, the two other are not

**Comment by Obicom** [comment]
rpi power must change from folder structure for new ha version 0.88.0 from /config/custom_components/sensor/rpi_power.py to /config/custom_components/rpi_power/sensor.py ... could this be the reason?

**Comment by ludeeus** [comment]
Yes, if you move it locally it will not show up before ca 1 day after the release is out of beta
