### ISSUE TITLE
v4.0.0 instructions

### ISSUE THREAD

**Issue by MightyMilster** [custom-components/custom_updater#85]
Re: v4.0.0 and above

Sorry if this is a dumb issue but I am having trouble understanding the instructions for v4. Firstly I am using Lovelace in YAML mode. 
My confusion comes from these two lines: 

> From this version you **NEED** to change your resource url's from `/local/` to `/customcards/` for all cards that you update with this component.
> 
> On your filesystem you will still place the cards under `/www/`, this change is **only** for under `resources` in your lovelace config.
> 

Is that relevant only if you are using Lovelace in **storage** mode?

My resource files are stored in a sub-folder of www, so my resource references look like this:
`- url: /local/cc/tracker-card.js`
`type: js`

Do I **NEED** to change this to 
` - url: /customcards/tracker-card.js`
`    type: js`

If I try that, my frontend, can't see the card anymore. However if I retain the original format (less versioning) it seems to work fine. Perhaps; when in YAML mode, you don't **NEED** to change your resource url's??

**Comment by ludeeus** [comment]
Yes you still need it, but you also need to keep the /cc/ part from your example

**Comment by MightyMilster** [comment]
So, like this?

`- url: /customcards/cc/tracker-card.js`

**Comment by ludeeus** [comment]
Looks correct

**Comment by ludeeus** [comment]
Did it help?

**Comment by MightyMilster** [comment]
Indeed it did help. **Thanks so much!!**

BTW, the latest version still says:
`VERSION = '4.0.1'`
should be...
`VERSION = '4.0.2'`

**Comment by ludeeus** [comment]
Changed to `4.0.3` about 2 hours ago ;)
<https://github.com/custom-components/custom_updater/blob/master/custom_components/custom_updater.py#L15>
