### ISSUE TITLE
New installation i cant get it to work. 

### ISSUE THREAD

**Issue by mshrem** [custom-components/custom_updater#92]
Ok so i followed and read the wiki but i cant seem to get this to work : 
 
I copied the .py file to my custom component folder and HA seems to recognize the component: 

`2019-02-21 11:39:40 WARNING (SyncWorker_5) [homeassistant.loader] You are using a custom component for custom_updater which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.`

But i can't seem to get it to work i get an error when trying to call the service custom_updater.check_all.

I am running on storage mode , here is the config file : 

custom_updater:
  mode: storage
  show_installable: False
  track:
   - components
  component_urls:
   - https://raw.githubusercontent.com/smartHomeHub/SmartIR/master/custom_components.json

So i cant seem to finish setting up the card am i missing something ?

**Comment by ludeeus** [comment]
As described in the issue template issues missing required information will be closed.
In this issue these are missing:

- Debug logs

**Comment by ludeeus** [comment]
Maybe a little hasty..

But I can't even start to see the issue if you do not give me the logs.

**Comment by mshrem** [comment]
Sure thing i can provide the logs give me a few mins

**Comment by mshrem** [comment]
`Error during setup of component custom_updaterTraceback (most recent call last):
  
```
File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 151, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/custom_updater.py", line 84, in async_setup
    hass, conf_hide_sensor, conf_component_urls)
  File "/config/custom_components/custom_updater.py", line 202, in __init__
    from pyupdate.ha_custom.custom_components import (
ModuleNotFoundError: No module named 'pyupdate'`
```

**Comment by ludeeus** [comment]
Restart Home Assistant

**Comment by mshrem** [comment]
Already did ... that error was during the first time setup .... i have no other logs regarding custom_updater and still doesnt show the custom_updater.check_all service

**Comment by ludeeus** [comment]
It fails to setup, so it will not register any services.

You can try to restart multiple times, or manually installing `pyupdate`

**Comment by mshrem** [comment]
Well i manually updated everything and now i am finally able to see the services.... now i just need to figure out how to install the card.

**Comment by mshrem** [comment]
So i cant get the card to install ..... is it ok if i ask for assistance here ??? or should i ask on the card git.

**Comment by ludeeus** [comment]
You already did, so closing this one.
https://github.com/custom-cards/tracker-card/issues/47

**Comment by sjtuross** [comment]
got the same issue after upgrading to 0.88

ModuleNotFoundError: No module named 'pyupdate'

restarted ha multiple times.

**Comment by ludeeus** [comment]
if restarts do not help (it should) you need to manually install `pyupdate`

**Comment by sjtuross** [comment]
I tried. Actually pyupdate exists in the deps folder in the config folder. it looks like ha doesn't load modules from that folder.

**Comment by ludeeus** [comment]
Delete it from that folder and try again restart

**Comment by sjtuross** [comment]
tried. same. just want to confirm if it's my issue or if it's a bug from ha 0.88

**Comment by ludeeus** [comment]
Not sure, I and many others run it with 0.88.
@sjtuross Open a separate issue and provide the info requested in the template.
