### ISSUE TITLE
No module named 'pyupdate' after upgrade to 0.88

### ISSUE THREAD

**Issue by sjtuross** [custom-components/custom_updater#94]
## Version of the custom_component

4.0.1
## Describe the bug
I upgraded from ha 0.87.1 to 0.88.0 then it stopped working. The custom component failed to load due to missing module pyupdate. restarted ha several times, cleaned the deps folder, still the same. The pyupdate module actually exists in the deps folder.

I use hass.io. Could that be the cause?

## `custom_updater` configuration

```yaml
custom_updater:
  track:
    - cards
    - components
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
```
```yaml
resources:
  - url: /local/mini-graph-card-bundle.js?v=0.2.1
    type: module
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
```

## Tracker-card configuration

```yaml
      - type: custom:tracker-card
```

## Debug log

```text
2019-02-22 17:00:56 ERROR (MainThread) [homeassistant.setup] Error during setup of component custom_updater
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 151, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/custom_updater.py", line 75, in async_setup
    hass, conf_hide_sensor, conf_card_urls, conf_mode)
  File "/config/custom_components/custom_updater.py", line 144, in __init__
    from pyupdate.ha_custom.custom_cards import CustomCards as Cards
ModuleNotFoundError: No module named 'pyupdate'
```

**Comment by ludeeus** [comment]
In the deps folder under bin do you have both python3.6 and python3.7?
if so, remove the python3.6 folder

**Comment by sjtuross** [comment]
Thank you. It works now. I do have another custom component which downloads a python module in the python 3.6 folder. why they can't coexist?

**Comment by ludeeus** [comment]
You are no longer runnig python3.6
Delete the entire python3.6 folder, and the other components should fix them self

**Comment by sjtuross** [comment]
Everything is working fine. Thanks so much!!
